### ISSUE TITLE
Maya crashes with daisy chain node inputs into Thunderloom

### ISSUE THREAD

**Issue by sharktacos** [Thunderloom/ThunderLoom#25]
Maya will crash if there are too many "daisy chain" connections into Thunderloom shader. 

For example if I connect a file texture to  the type1 spec color, this works fine (a into B). Further, if I connect a file texture to a VrayFalloff, then connect that to the type1 spec color (a into b into c) this also works fine. However if I add an additional step to the daisy chain: texture map > gamma > falloff > thunderloom spec (a into b into c into d), this will crash Maya. In other words if the daisy chain gets too long (three links) it crashes.

Work around is of course to minimize the node chain length.

**Comment by vidarn** [comment]
Hi Derek! Thanks for reporting this. I have been able to reproduce the crash and will try to find the cause.
Best regards,
Vidar

**Comment by vidarn** [comment]
I have fixed a bug which hopefully was the cause of these crashes. Would you mind trying to replace vray_thunderLoom.dll with the attached version and see if this fixes the issue?
[vray_thunderLoom.zip](https://github.com/Thunderloom/ThunderLoom/files/2714535/vray_thunderLoom.zip)
