### ISSUE TITLE
how to install ThunderLoom

### ISSUE THREAD

**Issue by madess** [Thunderloom/ThunderLoom#31]
hey! im new in 3dmax 2015- vray 3.0, i want to use "ThunderLoom"  is it possible? 
I already read several post here about installation, was like Chinese :D.. i really dont know Cmake, SDK, .... how to do it

**Comment by vidarn** [comment]
Hi madess, sorry for the late reply!.
I realize that the instructions are a bit unclear. The instructions describe how to compile the latest version of the plugin yourself. However, I guess most users will just want to install a pre-compiled version without any fuzz. 

You can find the latest compiled versions of the plugin here:
https://github.com/Thunderloom/ThunderLoom/releases

Unfortunately, the version for 3ds max there is a bit outdated and might be missing a few bug fixes. Please let me know if you run into any issues!
Vidar
