### ISSUE TITLE
Release for Vray Next

### ISSUE THREAD

**Issue by sharktacos** [Thunderloom/ThunderLoom#33]
Howdy,
Would it be possible to put up a Windows compile for Vray Next (for Maya 2017, 2018, 2019) on the Release page?

Thanks!

**Comment by vidarn** [comment]
Hi,
Sorry for the delay, but there's a build for V-Ray Next for Maya 2018 and 2019 on the release page now at least :)
We had some help by @rokn from Chaos Group so the shader should hopefully play a bit better with V-Ray now 👍

**Comment by StuffedDuck** [comment]
Hi there,
Any chance of also uploading versions for 3dsmax?

I attempted to compile a version for 3dsmax2019 and Vray Next but am currently stuck with some vutils_s.lib Linker Tool errors (LNK2038). 

Thanks!

**Comment by vidarn** [comment]
Hi StuffedDuck!
We compiled Thunderloom for 3ds Max 2019 and 2020, you can find it here:
https://github.com/Thunderloom/ThunderLoom/releases/tag/v0.94.0
Please let us know if there are any issues running it.
