### ISSUE TITLE
Thunderloom vray 3.6 for 3DS Max 2020

### ISSUE THREAD

**Issue by visualvlad** [Thunderloom/ThunderLoom#44]
Tried to build a 3DS Max 2020 vray 3.6 dlo unsuccessfully. could you please release a ready build for that version combination?

**Comment by petermcevoy** [comment]
@visualvlad Thanks for the report. I will try to get it going for those. 
I'm busy with other things at the moment so it will take a week or so. 

I'll keep you updated.

**Comment by visualvlad** [comment]
hello. we have now updated to vray 5 and no longer need the binary for 3.6. Thank you.

**Comment by vidarn** [comment]
Thanks for the update @visualvlad, closing this issue for now
